on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10
          architecture: x64

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: python3 manage.py test
