on:
  push:
    tags: ["!refs/tags/*"]
    branches: ['*']
    paths: ["*.py", "requirements.txt"]

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    container: python:3.10-bookworm
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          PGUSER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: python3 manage.py test
        env:
          POSTGRES_DB_LOGIN: postgres
          POSTGRES_DB_PASSWORD: postgres
          POSTGRES_DB_HOST: postgres
          POSTGRES_DB_PORT: 5432
          POSTGRES_DB_NAME: xops_test_db
          DJANGO_SECRET_KEY: 'cyhl=4u*!$!0r@kn9g9767afnu6dppt5q#*@t)u_+h(gy9d_!j'
          DJANGO_DEBUG: True
          DJANGO_ALLOWED_HOSTS: '127.0.0.1,localhost,172.17.0.1'
